# Generated by Django 5.0.7 on 2024-07-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0002_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="login",
            name="username",
        ),
        migrations.AddField(
            model_name="login",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="login",
            name="email",
            field=models.EmailField(max_length=128),
        ),
    ]
