# Generated by Django 5.0.7 on 2024-07-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0003_remove_login_username_login_name_alter_login_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Login",
        ),
    ]
